DROP TABLE IF EXISTS beers, cubes;

CREATE TABLE beers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  abv TEXT NOT NULL,
  color TEXT
);

CREATE TABLE cubes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dimensions TEXT NOT NULL,
  price TEXT
);